### ISSUE TITLE
NameError: name 'final' is not defined

### ISSUE THREAD

**Issue by rohandavidg** [ddhostallero/BiG-DRP#4]
Hi,

Thank you for creating this amazing tool. I seem to be running into an issue in trainer.py

command run:
python main.py --mode=train --folder=big --dataroot=data/

Output seen:
27      val-mse:0.7962  batch-mse:0.5520        val-r2:0.1694   batch-r2:0.5348 val-spearman:0.3993     19s
28      val-mse:0.8030  batch-mse:0.3361        val-r2:0.1623   batch-r2:0.5062 val-spearman:0.3919     18s
Traceback (most recent call last):
  File "main.py", line 40, in <module>
    main(args)
  File "main.py", line 15, in main
    main_fxn.main(FLAGS)
  File "/homes/rgnanaolivu/iBiG-DRP/bigdrp/main_cv.py", line 236, in main
    test_metrics = nested_cross_validation(FLAGS, drug_feats, cell_lines, labels, label_matrix, normalizer)
  File "/homes/rgnanaolivu/iBiG-DRP/bigdrp/main_cv.py", line 166, in nested_cross_validation
    val_error,_,_ = fold_validation(hp, FLAGS.seed, network, train_data, 
  File "/homes/rgnanaolivu/iBiG-DRP/bigdrp/main_cv.py", line 58, in fold_validation
    val_error, metric_names = trainer.fit(
File "/homes/rgnanaolivu/BiG-DRP/bigdrp/trainer.py", line 154, in fit
    if count == 10 and not final:
NameError: name 'final' is not defined

Thanks,
Rohan

**Comment by ddhostallero** [comment]
Thanks for letting me know. The repository has been updated.

-David
